### ISSUE TITLE
Support a Provenance filter

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#55]
As part of OI_CDM compatibility, ConceptQL needs to support a Provenance filter.  This filter will remove records from a stream based on whether the claim is defined as:
- Inpatient
- Outpatient
- Carrier
- Position (any positives integer)
- File type

**Comment by aguynamedryan** [comment]
What are the file types we want to provide as options?

**Comment by aguynamedryan** [comment]
If a result doesn't have corresponding provenance information, should we pass it through, or drop it?

**Comment by aguynamedryan** [comment]
Here is a list of all the types that are relevant to CDMv4.  I'm not sure how we can support most of these types in this operator.

[all_types.xlsx](https://github.com/outcomesinsights/conceptql/files/407815/all_types.xlsx)

For now should I limit provenance to procedure and condition?  We can always add features to it later.

**Comment by markdanese** [comment]
I think focusing on procedure and condition records makes the most sense.  I would definitely start with that.

**Comment by jenniferduryea** [comment]
agreed.  Procedure and condition are the main use cases we have.

**Comment by markdanese** [comment]
Should the Provenance operator have dropdown options?  What can be typed in this field?

**Comment by aguynamedryan** [comment]
Provenance supports ~10-15 "words" like "inpatient", "claim", "inpatient_primary_or_first", but also any concept_id a user might want to check for (so if they need the 2nd outpatient detail, they can enter that concept id).  They can enter in multiple values if they separate by commas.

Because of this concept_id support, it's hard to make a drop down menu.

In a future version, we could make a dropdown for the 10-15 "words" and have a text field for concept_ids, but I don't think we have time for that for this release.

**Comment by markdanese** [comment]
Is it possible to add some kind of text that indicates ```Enter text like "inpatient" or "outpatient", or enter a concept id``` to the label that appears in the operator?

**Comment by aguynamedryan** [comment]
Sure.  Someone, please provide the precise copy and I'll put it in the label.

**Comment by markdanese** [comment]
Filters incoming events to those matching the indicated provenance.  Enter the numeric concept id(s) for the provenance, or the corresponding text label(s) (e.g., "inpatient", "outpatient", "carrier", etc.)  Separate entries with commas.

**Comment by markdanese** [comment]
Filters incoming events to those matching the indicated provenance. Enter the numeric concept id(s) for the provenance, or the corresponding text label(s) (e.g., "inpatient", "outpatient", "carrier", etc.). Separate entries with commas.
(fixed typo added period)

**Comment by markdanese** [comment]
Actually, it only accepts a single value.  Commas won't work.

**Comment by aguynamedryan** [comment]
Commas should work now.

**Comment by aguynamedryan** [comment]
I've written several new tests and fixed up the operator.  I'm pretty confident this is working now.

**Comment by markdanese** [comment]
I still can't use a comma to separate the fields.  I am testing as outins at 3:19 pm Saturday.  I assume the changes have been propagated?

**Comment by aguynamedryan** [comment]
Commas should be working in the JAM now.

**Comment by markdanese** [comment]
Looks good now.  Tested as outins.  Tried inpatient, outpatient and it worked.  Also tried concept ids.

**Comment by marc-outins** [comment]
@aguynamedryan I created an algorithm using this operator and looking at the SQL it is including NULL in the list of type concept ids (in the operator I included inpatient and carrier):

WHERE (
            `provenance_type` IN (
                38000215,
                ......,
                44814640,
                NULL )

**Comment by aguynamedryan** [comment]
@marc-outins, "carrier" is not a supported keyword (despite the description of the operator).  I've updated the description with the correct keyword and created a validation to throw an error if a user specifies an incorrect keyword.

**Comment by marc-outins** [comment]
Adding back confirm to close tag after ryan explanation an updated text description

**Comment by jenniferduryea** [comment]
Confirmed the provenance filter works using "primary_or_first" short cut.  Also ensured the carrier 1st position concept_id is being accepted.  Looks good.  Closing out.
